[package]
name = "io-experiments"
version = "0.1.0"
edition = "2024"

[dependencies]
crc = "3.3.0"
io-uring = "0.7.7"
libc = "0.2.172"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
